name: Sync Bundle Bindings

on:
  schedule:
    - cron: '0 0 * * 0'  # every Sunday
  workflow_dispatch:

jobs:
  update-bindings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Update submodules
        run: |
          git submodule update --remote
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Bundle-Bindings
          git commit -m "Update Bundle-Bindings"
          git push
        continue-on-error: true
