name: Sync Bundle Bindings

on:
  schedule:
    - cron: '0 0 * * 0'  # every Sunday
  workflow_dispatch:

jobs:
  sync-bindings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update submodules and push
        run: |
          git submodule update --remote
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add api
          git commit -m "Updated Abutilon API Bindings" || echo "No updates to Abutilon API commited"

          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Abutilon-Engine/Abutilon-Bundle-Template.git

          git push origin HEAD

